engines:
  rubocop:
    enabled: true
    #checks:
    # Rubocop/Metrics/ClassLength:
    #   enabled: false

  eslint:
    enabled: true
  duplication:
    enabled: false

ratings:
  paths:
  - "**.js"

exclude_paths:
- spec/**/*
- **/*-test.js
